// Mock data for the Asterism design prototype.
// Mirrors the shape described in knowledge/contracts/data-model.md
// (repos are global metadata; tags / collections / notes are user-private).

export interface Repo {
  id: string;
  githubId: number;
  fullName: string;
  name: string;
  owner: string;
  description: string;
  language: string;
  topics: string[];
  stargazers: number;
  forks: number;
  homepage?: string;
  pushedAt: string; // ISO date
  repoCreatedAt: string;
  archived: boolean;
  isFork: boolean;
  starredAt: string;
  tagIds: string[];
  collectionIds: string[];
  note?: string;
}

export interface Tag {
  id: string;
  name: string;
  color: string; // token-friendly hue key
}

export interface Collection {
  id: string;
  name: string;
  description?: string;
}

// GitHub-ish language accent colors (kept as a small fixed palette).
export const LANGUAGE_COLORS: Record<string, string> = {
  TypeScript: '#3178c6',
  JavaScript: '#f1e05a',
  Rust: '#dea584',
  Go: '#00add8',
  Python: '#3572a5',
  'C++': '#f34b7d',
  Ruby: '#701516',
  Zig: '#ec915c',
  Shell: '#89e051',
  Vue: '#41b883',
  Svelte: '#ff3e00',
};

export const TAGS: Tag[] = [
  { id: 't1', name: 'must-read', color: 'amber' },
  { id: 't2', name: 'ai', color: 'violet' },
  { id: 't3', name: 'devtools', color: 'sky' },
  { id: 't4', name: 'frontend', color: 'emerald' },
  { id: 't5', name: 'backend', color: 'rose' },
  { id: 't6', name: 'learning', color: 'orange' },
  { id: 't7', name: 'inspiration', color: 'cyan' },
];

export const COLLECTIONS: Collection[] = [
  { id: 'c1', name: '前端武器库', description: '构建现代 Web 界面的核心工具与框架' },
  { id: 'c2', name: 'AI / LLM', description: '大模型、推理、Agent 相关项目' },
  { id: 'c3', name: '基础设施', description: '数据库、运行时、部署与可观测性' },
  { id: 'c4', name: '想读的源码', description: '准备深入阅读源码的高质量项目' },
];

function daysAgo(n: number): string {
  const d = new Date('2026-06-29T00:00:00Z');
  d.setUTCDate(d.getUTCDate() - n);
  return d.toISOString();
}

export const REPOS: Repo[] = [
  {
    id: 'r1',
    githubId: 70107786,
    fullName: 'vercel/next.js',
    name: 'next.js',
    owner: 'vercel',
    description: 'The React Framework for the Web — used by some of the world\u2019s largest companies.',
    language: 'JavaScript',
    topics: ['react', 'framework', 'ssr', 'web'],
    stargazers: 128400,
    forks: 27300,
    homepage: 'https://nextjs.org',
    pushedAt: daysAgo(1),
    repoCreatedAt: '2016-10-05',
    archived: false,
    isFork: false,
    starredAt: daysAgo(40),
    tagIds: ['t1', 't4'],
    collectionIds: ['c1'],
    note: '团队主力框架。App Router 的缓存语义值得反复读文档。',
  },
  {
    id: 'r2',
    githubId: 10270250,
    fullName: 'facebook/react',
    name: 'react',
    owner: 'facebook',
    description: 'The library for web and native user interfaces.',
    language: 'JavaScript',
    topics: ['ui', 'library', 'frontend', 'declarative'],
    stargazers: 232100,
    forks: 47600,
    homepage: 'https://react.dev',
    pushedAt: daysAgo(2),
    repoCreatedAt: '2013-05-24',
    archived: false,
    isFork: false,
    starredAt: daysAgo(120),
    tagIds: ['t1', 't4'],
    collectionIds: ['c1'],
  },
  {
    id: 'r3',
    githubId: 24195339,
    fullName: 'rust-lang/rust',
    name: 'rust',
    owner: 'rust-lang',
    description: 'Empowering everyone to build reliable and efficient software.',
    language: 'Rust',
    topics: ['compiler', 'systems', 'language'],
    stargazers: 99800,
    forks: 12900,
    homepage: 'https://www.rust-lang.org',
    pushedAt: daysAgo(1),
    repoCreatedAt: '2010-06-16',
    archived: false,
    isFork: false,
    starredAt: daysAgo(200),
    tagIds: ['t6'],
    collectionIds: ['c3', 'c4'],
    note: '系统编程学习主线，所有权模型笔记见 Notion。',
  },
  {
    id: 'r4',
    githubId: 65600975,
    fullName: 'pytorch/pytorch',
    name: 'pytorch',
    owner: 'pytorch',
    description: 'Tensors and dynamic neural networks in Python with strong GPU acceleration.',
    language: 'Python',
    topics: ['deep-learning', 'machine-learning', 'gpu', 'tensor'],
    stargazers: 84600,
    forks: 22800,
    homepage: 'https://pytorch.org',
    pushedAt: daysAgo(1),
    repoCreatedAt: '2016-08-13',
    archived: false,
    isFork: false,
    starredAt: daysAgo(60),
    tagIds: ['t2'],
    collectionIds: ['c2'],
  },
  {
    id: 'r5',
    githubId: 155220641,
    fullName: 'langchain-ai/langchain',
    name: 'langchain',
    owner: 'langchain-ai',
    description: 'Build context-aware reasoning applications with LLMs.',
    language: 'Python',
    topics: ['llm', 'ai', 'agents', 'rag'],
    stargazers: 96200,
    forks: 15600,
    homepage: 'https://langchain.com',
    pushedAt: daysAgo(3),
    repoCreatedAt: '2022-10-17',
    archived: false,
    isFork: false,
    starredAt: daysAgo(30),
    tagIds: ['t2', 't1'],
    collectionIds: ['c2'],
    note: 'Agent 编排参考。注意它抽象层偏厚，生产里按需裁剪。',
  },
  {
    id: 'r6',
    githubId: 41881900,
    fullName: 'microsoft/vscode',
    name: 'vscode',
    owner: 'microsoft',
    description: 'Visual Studio Code — open source code editor redefining editing.',
    language: 'TypeScript',
    topics: ['editor', 'electron', 'devtools'],
    stargazers: 163700,
    forks: 28900,
    homepage: 'https://code.visualstudio.com',
    pushedAt: daysAgo(1),
    repoCreatedAt: '2015-09-03',
    archived: false,
    isFork: false,
    starredAt: daysAgo(300),
    tagIds: ['t3'],
    collectionIds: ['c1'],
  },
  {
    id: 'r7',
    githubId: 50278681,
    fullName: 'denoland/deno',
    name: 'deno',
    owner: 'denoland',
    description: 'A modern runtime for JavaScript and TypeScript.',
    language: 'Rust',
    topics: ['runtime', 'typescript', 'javascript', 'v8'],
    stargazers: 98100,
    forks: 5400,
    homepage: 'https://deno.com',
    pushedAt: daysAgo(2),
    repoCreatedAt: '2018-05-13',
    archived: false,
    isFork: false,
    starredAt: daysAgo(90),
    tagIds: ['t3'],
    collectionIds: ['c3'],
  },
  {
    id: 'r8',
    githubId: 27193779,
    fullName: 'nodejs/node',
    name: 'node',
    owner: 'nodejs',
    description: 'Node.js JavaScript runtime built on V8.',
    language: 'JavaScript',
    topics: ['runtime', 'javascript', 'server'],
    stargazers: 108900,
    forks: 30700,
    homepage: 'https://nodejs.org',
    pushedAt: daysAgo(1),
    repoCreatedAt: '2014-11-26',
    archived: false,
    isFork: false,
    starredAt: daysAgo(250),
    tagIds: ['t5'],
    collectionIds: ['c3'],
  },
  {
    id: 'r9',
    githubId: 83222441,
    fullName: 'tailwindlabs/tailwindcss',
    name: 'tailwindcss',
    owner: 'tailwindlabs',
    description: 'A utility-first CSS framework for rapid UI development.',
    language: 'TypeScript',
    topics: ['css', 'frontend', 'design', 'utility'],
    stargazers: 84300,
    forks: 4300,
    homepage: 'https://tailwindcss.com',
    pushedAt: daysAgo(4),
    repoCreatedAt: '2017-10-23',
    archived: false,
    isFork: false,
    starredAt: daysAgo(45),
    tagIds: ['t4', 't1'],
    collectionIds: ['c1'],
  },
  {
    id: 'r10',
    githubId: 11730342,
    fullName: 'vuejs/vue',
    name: 'vue',
    owner: 'vuejs',
    description: 'This is the repo for Vue 2. For Vue 3, see the vuejs/core repo.',
    language: 'JavaScript',
    topics: ['frontend', 'framework', 'reactive'],
    stargazers: 208500,
    forks: 33700,
    homepage: 'https://vuejs.org',
    pushedAt: daysAgo(420),
    repoCreatedAt: '2013-07-29',
    archived: true,
    isFork: false,
    starredAt: daysAgo(500),
    tagIds: ['t4'],
    collectionIds: [],
  },
  {
    id: 'r11',
    githubId: 80990478,
    fullName: 'ollama/ollama',
    name: 'ollama',
    owner: 'ollama',
    description: 'Get up and running with large language models locally.',
    language: 'Go',
    topics: ['llm', 'ai', 'local', 'inference'],
    stargazers: 92700,
    forks: 7300,
    homepage: 'https://ollama.com',
    pushedAt: daysAgo(2),
    repoCreatedAt: '2023-06-26',
    archived: false,
    isFork: false,
    starredAt: daysAgo(20),
    tagIds: ['t2', 't1'],
    collectionIds: ['c2'],
    note: '本地跑模型首选。配合 BYOK 思路做离线兜底。',
  },
  {
    id: 'r12',
    githubId: 1334369,
    fullName: 'torvalds/linux',
    name: 'linux',
    owner: 'torvalds',
    description: 'Linux kernel source tree.',
    language: 'C++',
    topics: ['kernel', 'os', 'systems'],
    stargazers: 184200,
    forks: 54100,
    pushedAt: daysAgo(1),
    repoCreatedAt: '2011-09-04',
    archived: false,
    isFork: false,
    starredAt: daysAgo(600),
    tagIds: ['t6'],
    collectionIds: ['c4'],
  },
  {
    id: 'r13',
    githubId: 156018,
    fullName: 'postgres/postgres',
    name: 'postgres',
    owner: 'postgres',
    description: 'Mirror of the official PostgreSQL GIT repository.',
    language: 'C++',
    topics: ['database', 'sql', 'rdbms'],
    stargazers: 17600,
    forks: 4600,
    homepage: 'https://www.postgresql.org',
    pushedAt: daysAgo(1),
    repoCreatedAt: '2010-09-21',
    archived: false,
    isFork: false,
    starredAt: daysAgo(150),
    tagIds: ['t5'],
    collectionIds: ['c3'],
  },
  {
    id: 'r14',
    githubId: 33645537,
    fullName: 'sveltejs/svelte',
    name: 'svelte',
    owner: 'sveltejs',
    description: 'web development for the rest of us.',
    language: 'Svelte',
    topics: ['frontend', 'framework', 'compiler'],
    stargazers: 82900,
    forks: 4400,
    homepage: 'https://svelte.dev',
    pushedAt: daysAgo(3),
    repoCreatedAt: '2016-11-20',
    archived: false,
    isFork: false,
    starredAt: daysAgo(70),
    tagIds: ['t4', 't7'],
    collectionIds: ['c1'],
  },
  {
    id: 'r15',
    githubId: 28457823,
    fullName: 'ziglang/zig',
    name: 'zig',
    owner: 'ziglang',
    description: 'General-purpose programming language and toolchain for maintaining robust, optimal software.',
    language: 'Zig',
    topics: ['language', 'systems', 'compiler'],
    stargazers: 38200,
    forks: 2800,
    homepage: 'https://ziglang.org',
    pushedAt: daysAgo(5),
    repoCreatedAt: '2015-08-08',
    archived: false,
    isFork: false,
    starredAt: daysAgo(110),
    tagIds: ['t6', 't7'],
    collectionIds: ['c4'],
  },
  {
    id: 'r16',
    githubId: 5101141,
    fullName: 'rails/rails',
    name: 'rails',
    owner: 'rails',
    description: 'Ruby on Rails — a web-application framework that includes everything needed to create database-backed web apps.',
    language: 'Ruby',
    topics: ['framework', 'web', 'mvc', 'backend'],
    stargazers: 56700,
    forks: 21600,
    homepage: 'https://rubyonrails.org',
    pushedAt: daysAgo(2),
    repoCreatedAt: '2008-04-11',
    archived: false,
    isFork: false,
    starredAt: daysAgo(180),
    tagIds: ['t5'],
    collectionIds: [],
  },
  {
    id: 'r17',
    githubId: 920161,
    fullName: 'kubernetes/kubernetes',
    name: 'kubernetes',
    owner: 'kubernetes',
    description: 'Production-Grade Container Scheduling and Management.',
    language: 'Go',
    topics: ['containers', 'orchestration', 'cloud', 'infra'],
    stargazers: 113800,
    forks: 40500,
    homepage: 'https://kubernetes.io',
    pushedAt: daysAgo(1),
    repoCreatedAt: '2014-06-06',
    archived: false,
    isFork: false,
    starredAt: daysAgo(140),
    tagIds: ['t5', 't1'],
    collectionIds: ['c3'],
  },
  {
    id: 'r18',
    githubId: 143112372,
    fullName: 'shadcn-ui/ui',
    name: 'ui',
    owner: 'shadcn-ui',
    description: 'Beautifully designed components that you can copy and paste into your apps.',
    language: 'TypeScript',
    topics: ['ui', 'components', 'react', 'tailwind'],
    stargazers: 78900,
    forks: 5200,
    homepage: 'https://ui.shadcn.com',
    pushedAt: daysAgo(2),
    repoCreatedAt: '2023-01-04',
    archived: false,
    isFork: false,
    starredAt: daysAgo(15),
    tagIds: ['t4', 't7', 't1'],
    collectionIds: ['c1'],
    note: '本项目设计系统的基底。',
  },
  {
    id: 'r19',
    githubId: 21737465,
    fullName: 'huggingface/transformers',
    name: 'transformers',
    owner: 'huggingface',
    description: 'State-of-the-art Machine Learning for PyTorch, TensorFlow, and JAX.',
    language: 'Python',
    topics: ['nlp', 'ai', 'transformers', 'models'],
    stargazers: 137600,
    forks: 27600,
    homepage: 'https://huggingface.co/transformers',
    pushedAt: daysAgo(1),
    repoCreatedAt: '2018-10-29',
    archived: false,
    isFork: false,
    starredAt: daysAgo(50),
    tagIds: ['t2'],
    collectionIds: ['c2', 'c4'],
  },
  {
    id: 'r20',
    githubId: 11894387,
    fullName: 'mrdoob/three.js',
    name: 'three.js',
    owner: 'mrdoob',
    description: 'JavaScript 3D Library.',
    language: 'JavaScript',
    topics: ['3d', 'webgl', 'graphics', 'frontend'],
    stargazers: 105100,
    forks: 35600,
    homepage: 'https://threejs.org',
    pushedAt: daysAgo(2),
    repoCreatedAt: '2010-03-23',
    archived: false,
    isFork: false,
    starredAt: daysAgo(85),
    tagIds: ['t4', 't7'],
    collectionIds: [],
  },
  {
    id: 'r21',
    githubId: 3506011,
    fullName: 'fish-shell/fish-shell',
    name: 'fish-shell',
    owner: 'fish-shell',
    description: 'The user-friendly command line shell.',
    language: 'Rust',
    topics: ['shell', 'cli', 'devtools'],
    stargazers: 30100,
    forks: 2500,
    homepage: 'https://fishshell.com',
    pushedAt: daysAgo(8),
    repoCreatedAt: '2012-01-29',
    archived: false,
    isFork: false,
    starredAt: daysAgo(95),
    tagIds: ['t3'],
    collectionIds: [],
  },
  {
    id: 'r22',
    githubId: 28809201,
    fullName: 'prettier/prettier',
    name: 'prettier',
    owner: 'prettier',
    description: 'Prettier is an opinionated code formatter.',
    language: 'JavaScript',
    topics: ['formatter', 'devtools', 'javascript'],
    stargazers: 49800,
    forks: 4400,
    homepage: 'https://prettier.io',
    pushedAt: daysAgo(12),
    repoCreatedAt: '2017-01-10',
    archived: false,
    isFork: false,
    starredAt: daysAgo(160),
    tagIds: ['t3'],
    collectionIds: [],
  },
  {
    id: 'r23',
    githubId: 47359575,
    fullName: 'gin-gonic/gin',
    name: 'gin',
    owner: 'gin-gonic',
    description: 'Gin is a HTTP web framework written in Go.',
    language: 'Go',
    topics: ['web', 'framework', 'http', 'backend'],
    stargazers: 79200,
    forks: 8200,
    homepage: 'https://gin-gonic.com',
    pushedAt: daysAgo(6),
    repoCreatedAt: '2014-06-16',
    archived: false,
    isFork: false,
    starredAt: daysAgo(75),
    tagIds: ['t5'],
    collectionIds: ['c3'],
  },
  {
    id: 'r24',
    githubId: 7508411,
    fullName: 'jquery/jquery',
    name: 'jquery',
    owner: 'jquery',
    description: 'jQuery JavaScript Library.',
    language: 'JavaScript',
    topics: ['library', 'dom', 'legacy'],
    stargazers: 59600,
    forks: 20500,
    homepage: 'https://jquery.com',
    pushedAt: daysAgo(380),
    repoCreatedAt: '2009-04-03',
    archived: true,
    isFork: false,
    starredAt: daysAgo(700),
    tagIds: [],
    collectionIds: [],
  },
];

// ---- Derived helpers ----

export const ALL_LANGUAGES = Array.from(new Set(REPOS.map((r) => r.language))).sort();

export const ALL_TOPICS = Array.from(new Set(REPOS.flatMap((r) => r.topics))).sort();

export function formatStars(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
  return String(n);
}

export function relativeTime(iso: string): string {
  const now = new Date('2026-06-29T00:00:00Z').getTime();
  const then = new Date(iso).getTime();
  const days = Math.round((now - then) / 86400000);
  if (days <= 0) return '今天';
  if (days === 1) return '昨天';
  if (days < 30) return `${days} 天前`;
  if (days < 365) return `${Math.round(days / 30)} 个月前`;
  return `${Math.round(days / 365)} 年前`;
}

// Stats for dashboard
export const LANGUAGE_DISTRIBUTION = ALL_LANGUAGES.map((lang) => ({
  language: lang,
  count: REPOS.filter((r) => r.language === lang).length,
})).sort((a, b) => b.count - a.count);

export const TOP_TOPICS = (() => {
  const counts = new Map<string, number>();
  for (const r of REPOS) for (const t of r.topics) counts.set(t, (counts.get(t) ?? 0) + 1);
  return Array.from(counts.entries())
    .map(([topic, count]) => ({ topic, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 8);
})();

// Stars added per month over the last 8 months (mock trend).
export const STAR_TIMELINE = [
  { month: '2025-11', count: 8 },
  { month: '2025-12', count: 14 },
  { month: '2026-01', count: 11 },
  { month: '2026-02', count: 19 },
  { month: '2026-03', count: 23 },
  { month: '2026-04', count: 17 },
  { month: '2026-05', count: 28 },
  { month: '2026-06', count: 21 },
];
